title: <div style="text-align: center;">
    <h1>Laurence Spekterman</h1>
</div>
logo: /assets:img/circle_headshot.png
#description: Former Teacher, Data Analytics, Marketing
#show_downloads: true
theme: jekyll-theme-minimal
